export const menuData = {
  "First Bites": [
    { name: "Wonton (5 pcs)", price: "150" },
    { name: "Garlic Mushroom (Half)", price: "180" },
    { name: "Garlic Mushroom (Full)", price: "320" },
    { name: "Chicken Cashew Nut Salad", price: "380" },
    { name: "Greek Salad", price: "320" },
    { name: "Olive Tracky Salad", price: "350" },
  ],
  "Hot & Fried": [
    { name: "Crispy Fried Chicken", price: "120" },
    { name: "Crispy Fried Chicken (5 pcs)", price: "500" },
    { name: "Thai Fried Chicken", price: "120" },
    { name: "Thai Fried Chicken (5 pcs)", price: "500" },
    { name: "Hot & Spicy Wings (6 pcs)", price: "270" },
    { name: "Crispy Wings (6 pcs)", price: "250" },
    { name: "French Fries", price: "150" },
    { name: "Nachos", price: "250" },
    { name: "Chicken Poppers", price: "250" },
    { name: "Grilled Tandoori with Buttery Paratha", price: "200" },
    { name: "Masala Chicken with Buttery Paratha", price: "220" },
  ],
  "Pasta": [
    { name: "White Sauce Pasta", price: "260" },
    { name: "Pan Pasta", price: "280" },
    { name: "Mexican Spicy Pasta", price: "280" },
    { name: "Naga Pasta", price: "300" },
    { name: "Pasta Basta", price: "320" },
    { name: "Pasta Italiano", price: "290" },
    { name: "23 Special", price: "350" },
  ],
  "Meal Deal": [
    { name: "Chicken Steak", price: "400", note: "with Fried Rice, Vegetable, Garlic Mushroom + Cold Drink" },
    { name: "Chicken Fried Rice", price: "300", note: "with Fried Rice, Fried Chicken, Vegetable + Cold Drink" },
    { name: "Vegetable Fried Rice", price: "250", note: "with Fried Rice, Chicken Chilli Onion, Vegetable + Cold Drink" },
    { name: "Tandoori Chicken", price: "350", note: "with Fried Rice, Tandoori Chicken, Vegetable + Cold Drink" },
    { name: "Chicken Katsu", price: "420", note: "with Fried Rice, Chicken Katsu, Vegetable + Cold Drink" },
    { name: "Couple Platter", price: "650", note: "with 2 Fried Rice, 2 Tandoori Chicken, 2 Vegetable + 2 Cold Drink" },
  ],
  "Pizza": [
    { name: "Cheese Lover's (6\")", price: "350" },
    { name: "Cheese Lover's (8\")", price: "520" },
    { name: "Cheese Lover's (10\")", price: "680" },
    { name: "Cheese Lover's (12\")", price: "780" },
    { name: "B.B.Q Meat Machine (6\")", price: "370" },
    { name: "B.B.Q Meat Machine (8\")", price: "550" },
    { name: "B.B.Q Meat Machine (10\")", price: "700" },
    { name: "B.B.Q Meat Machine (12\")", price: "800" },
    { name: "Sausage Carnival (6\")", price: "350" },
    { name: "Sausage Carnival (8\")", price: "520" },
    { name: "Sausage Carnival (10\")", price: "690" },
    { name: "Sausage Carnival (12\")", price: "790" },
    { name: "Pizza Margherita (8\")", price: "430" },
    { name: "Pizza Margherita (10\")", price: "580" },
    { name: "Pizza Margherita (12\")", price: "680" },
    { name: "Hot Dog Pizza (10\")", price: "800" },
    { name: "Hot Dog Pizza (12\")", price: "900" },
    { name: "Ring Cheese Pizza (10\")", price: "790" },
    { name: "Ring Cheese Pizza (12\")", price: "890" },
    { name: "23 Spical Pizza (12\")", price: "950" },
  ],
  "Chowmein & Ramen": [
    { name: "Chicken Chowmein (1:1)", price: "220" },
    { name: "Chicken Chowmein (1:3)", price: "600" },
    { name: "Vegetable Chowmein (1:1)", price: "170" },
    { name: "Vegetable Chowmein (1:3)", price: "480" },
    { name: "Special Ramen", price: "420" },
    { name: "Naga Ramen", price: "370" },
  ],
  "Soup": [
    { name: "Thai Soup (1:1)", price: "180" },
    { name: "Thai Soup (1:2)", price: "330" },
    { name: "Thai Soup (1:3)", price: "500" },
    { name: "Corn Soup (1:1)", price: "160" },
    { name: "Corn Soup (1:2)", price: "300" },
    { name: "Corn Soup (1:3)", price: "450" },
    { name: "Clear Soup (1:1)", price: "170" },
    { name: "Clear Soup (1:2)", price: "310" },
    { name: "Clear Soup (1:3)", price: "460" },
    { name: "Cream of Mushroom", price: "200" },
  ],
  "Shawarma": [
    { name: "Platform 23 Special Shawarma", price: "180" },
    { name: "Vegetable Shawarma", price: "140" },
    { name: "BBQ Chicken Shawarma", price: "200" },
  ],
  "Rice Bowl": [
    { name: "BBQ Rice Bowl", price: "170" },
  ],
  "Burger": [
    { name: "Classic Chicken Burger", price: "220" },
    { name: "BBQ Cheese Burger", price: "270" },
    { name: "Double Decker Cheese Burger", price: "250" },
  ],
  "Sandwich": [
    { name: "Smoked Grilled Chicken Sandwich", price: "300" },
    { name: "Sub Sandwich", price: "250" },
  ],
  "Energizing Treat": [
    { name: "Hot Coffee", price: "120" },
    { name: "Cappuccino", price: "190" },
    { name: "Mocha", price: "200" },
    { name: "Hot Chocolate", price: "250" },
    { name: "Americano", price: "150" },
    { name: "Iced Americano", price: "200" },
    { name: "Espresso (Single Shot)", price: "140" },
    { name: "Espresso (Double Shot)", price: "200" },
    { name: "Affogato", price: "250" },
  ],
  "Frosty Sips": [
    { name: "Cold Coffee", price: "170" },
    { name: "Choco Cold Coffee", price: "190" },
    { name: "Kitkat Shake", price: "200" },
    { name: "Oreo Shake", price: "190" },
    { name: "Chocolate Milk Shake", price: "200" },
    { name: "Strawberry Shake", price: "190" },
    { name: "Vanilla Shake", price: "170" },
    { name: "Nutty Delights", price: "230" },
  ],
  "Refreshers": [
    { name: "Lemonade", price: "120" },
    { name: "Brazilian Lemonade", price: "220" },
    { name: "Orange Juice", price: "160" },
  ],
  "Moktails": [
    { name: "Slytherin", price: "200" },
    { name: "Gryffindor", price: "200" },
    { name: "Hufflepuff", price: "200" },
    { name: "Ravenclaw", price: "200" },
  ],
  "Sweet Tooth": [
    { name: "Ice Cream", price: "130" },
  ],
};

export const categories = Object.keys(menuData);
